# LEVEL 15 - AI Workload Security
# GPU Workload Protection
# ------------------------
# Secures machine learning workloads with specific needs:
# - Access to GPU resources
# - ML platform endpoints
# - Specialized ports for tools like Jupyter/TensorBoard
# Restricts traffic to approved ML services and internal GPU networks
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-workload-protection
spec:
  podSelector:
    matchLabels:
      workload-type: gpu
  egress:
  - to:
    - dnsName: "*.ml.cloud-provider.com"  # ML service endpoints
    ports:
    - port: 8888-8890                    # Port range for Jupyter/Lab
    - port: 6006                         # TensorBoard port
  - to:
    - ipBlock:
        cidr: 192.168.200.0/24           # GPU node network 