title: Kubernetes Network Policies
description: A comprehensive guide to Kubernetes Network Policies with practical examples
baseurl: "/k8s-network-policies"
url: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0

collections:
  policies:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "policies"
      type: "policies"
    values:
      layout: "policy"

include:
  - policies
  - _policies
  - scripts

# ... rest of the file remains unchanged ... 