title: Kubernetes Network Policies
description: A comprehensive guide to Kubernetes Network Policies with practical examples
baseurl: "/k8s-network-policies"
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

collections:
  policies:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "policies"
    values:
      layout: "policy" 